/* Login page theme tokens — shared across auth components */
export const T = {
    /* backgrounds */
    pageBg: "linear-gradient(135deg, #eef5ff 0%, #f3f6ff 52%, #ffffff 100%)",
    orbA: "radial-gradient(circle, #c7d2fe, #a5b4fc)",
    orbB: "radial-gradient(circle, #ddd6fe, #c4b5fd)",
    orbC: "radial-gradient(circle, #bfdbfe, #93c5fd)",
    cardBg: "#ffffff",
    cardBorder: "#e5e7eb",

    /* brand */
    primary: "#4f46e5",
    primaryHov: "#4338ca",
    accent: "#7c3aed",
    accentHov: "#6d28d9",

    /* text */
    textDark: "#1f2937",
    textMid: "#6b7280",
    textLight: "#9ca3af",

    /* inputs */
    inputBorder: "#d1d5db",
    inputBorderFocus: "#6366f1",
    inputShadowFocus: "rgba(99,102,241,0.15)",

    /* utility */
    dividerLine: "#e5e7eb",
    warnBg: "#fffbeb",
    warnBorder: "#fde68a",
    warnText: "#92400e",
};

/* Login page inline style objects */
export const S = {
    page: {
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "1.5rem 1rem",
        position: "relative",
        overflow: "hidden",
        background: T.pageBg,
    },
    orb: (size, top, left, color, delay) => ({
        position: "absolute",
        width: size,
        height: size,
        borderRadius: "50%",
        background: color,
        top,
        left,
        filter: "blur(70px)",
        opacity: 0.55,
        animation: `floatOrb 9s ease-in-out ${delay} infinite alternate`,
        pointerEvents: "none",
    }),
    card: {
        position: "relative",
        zIndex: 10,
        width: "100%",
        maxWidth: "420px",
        borderRadius: "24px",
        background: T.cardBg,
        border: `1px solid ${T.cardBorder}`,
        boxShadow: "0 20px 60px rgba(79,70,229,0.1), 0 4px 16px rgba(15,23,42,0.06)",
        padding: "2.25rem 2rem",
    },
    logo: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "0.6rem",
        marginBottom: "0.45rem",
    },
    logoIcon: {
        width: 44,
        height: 44,
        borderRadius: "14px",
        background: "linear-gradient(135deg, #a78bfa, #6366f1)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "1.45rem",
        boxShadow: "0 4px 14px rgba(99,102,241,0.35)",
    },
    logoText: {
        fontSize: "1.35rem",
        fontWeight: 800,
        color: T.primary,
        letterSpacing: "-0.02em",
    },
    tagline: {
        textAlign: "center",
        color: T.textMid,
        fontSize: "0.8rem",
        marginBottom: "1.75rem",
    },
    tabs: {
        display: "flex",
        background: "#f3f4f6",
        borderRadius: "14px",
        padding: "4px",
        marginBottom: "1.6rem",
        border: "1px solid #e5e7eb",
    },
    tab: (active) => ({
        flex: 1,
        padding: "0.55rem",
        borderRadius: "10px",
        border: "none",
        cursor: "pointer",
        fontFamily: "inherit",
        fontSize: "0.875rem",
        fontWeight: 600,
        transition: "all 0.25s ease",
        background: active ? "linear-gradient(135deg, #818cf8, #6366f1)" : "transparent",
        color: active ? "#fff" : T.textMid,
        boxShadow: active ? "0 2px 10px rgba(99,102,241,0.35)" : "none",
    }),
    fieldWrap: { marginBottom: "0.95rem" },
    label: {
        display: "block",
        fontSize: "0.72rem",
        fontWeight: 700,
        color: T.textMid,
        letterSpacing: "0.06em",
        textTransform: "uppercase",
        marginBottom: "0.4rem",
    },
    input: {
        width: "100%",
        background: "#fafafa",
        border: `1px solid ${T.inputBorder}`,
        borderRadius: "12px",
        padding: "0.78rem 1rem",
        color: T.textDark,
        fontSize: "0.92rem",
        outline: "none",
        fontFamily: "inherit",
        transition: "border-color 0.2s, box-shadow 0.2s",
        boxSizing: "border-box",
    },
    inputFocus: {
        borderColor: T.inputBorderFocus,
        boxShadow: `0 0 0 3px ${T.inputShadowFocus}`,
        background: "#fff",
    },
    pwWrap: { position: "relative" },
    eyeBtn: {
        position: "absolute",
        right: "0.85rem",
        top: "50%",
        transform: "translateY(-50%)",
        background: "none",
        border: "none",
        cursor: "pointer",
        color: T.textLight,
        fontSize: "1.05rem",
        padding: 0,
        lineHeight: 1,
    },
    primaryBtn: (loading) => ({
        width: "100%",
        padding: "0.82rem",
        borderRadius: "14px",
        border: "none",
        cursor: loading ? "not-allowed" : "pointer",
        fontFamily: "inherit",
        fontSize: "0.95rem",
        fontWeight: 700,
        color: "#fff",
        background: loading
            ? "#c7d2fe"
            : "linear-gradient(135deg, #818cf8 0%, #6366f1 50%, #4f46e5 100%)",
        boxShadow: loading ? "none" : "0 4px 18px rgba(99,102,241,0.4)",
        transition: "all 0.25s ease",
        marginTop: "0.5rem",
    }),
    forgotBtn: {
        background: "none",
        border: "none",
        color: T.primary,
        cursor: "pointer",
        fontSize: "0.78rem",
        fontWeight: 600,
        fontFamily: "inherit",
        padding: 0,
        marginTop: "0.4rem",
        display: "block",
        marginLeft: "auto",
        transition: "color 0.2s",
    },
    divider: {
        display: "flex",
        alignItems: "center",
        gap: "0.75rem",
        margin: "1.2rem 0",
        color: T.textLight,
        fontSize: "0.72rem",
        fontWeight: 600,
        letterSpacing: "0.06em",
        textTransform: "uppercase",
    },
    dividerLine: {
        flex: 1,
        height: "1px",
        background: T.dividerLine,
    },
    googleBtn: {
        width: "100%",
        padding: "0.78rem",
        borderRadius: "14px",
        border: `1px solid ${T.cardBorder}`,
        background: "#fff",
        color: T.textDark,
        cursor: "pointer",
        fontFamily: "inherit",
        fontSize: "0.88rem",
        fontWeight: 600,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "0.55rem",
        transition: "background 0.2s, border-color 0.2s, box-shadow 0.2s",
        marginBottom: "0.65rem",
        boxShadow: "0 1px 4px rgba(15,23,42,0.06)",
    },
    anonBtn: {
        width: "100%",
        padding: "0.72rem",
        borderRadius: "14px",
        border: "1px solid #e5e7eb",
        background: "#f9fafb",
        color: T.textMid,
        cursor: "pointer",
        fontFamily: "inherit",
        fontSize: "0.83rem",
        fontWeight: 500,
        transition: "background 0.2s, color 0.2s",
    },
    verifyBanner: {
        background: T.warnBg,
        border: `1px solid ${T.warnBorder}`,
        borderRadius: "14px",
        padding: "0.9rem 1rem",
        marginTop: "1rem",
    },
    verifyText: {
        color: T.warnText,
        fontSize: "0.8rem",
        fontWeight: 500,
        marginBottom: "0.65rem",
    },
    resendBtn: {
        width: "100%",
        padding: "0.65rem",
        borderRadius: "10px",
        border: "1px solid #fde68a",
        background: "#fef3c7",
        color: T.warnText,
        cursor: "pointer",
        fontFamily: "inherit",
        fontSize: "0.82rem",
        fontWeight: 600,
        transition: "background 0.2s",
    },
    toast: (type) => ({
        position: "fixed",
        top: "1.5rem",
        right: "1.5rem",
        zIndex: 999,
        background: type === "error"
            ? "#fee2e2"
            : type === "warn"
                ? "#fef3c7"
                : "#d1fae5",
        color: type === "error"
            ? "#991b1b"
            : type === "warn"
                ? "#92400e"
                : "#065f46",
        border: type === "error"
            ? "1px solid #fca5a5"
            : type === "warn"
                ? "1px solid #fde68a"
                : "1px solid #6ee7b7",
        borderRadius: "14px",
        padding: "0.85rem 1.2rem",
        fontSize: "0.85rem",
        fontWeight: 600,
        maxWidth: "340px",
        boxShadow: "0 8px 32px rgba(15,23,42,0.12)",
        display: "flex",
        alignItems: "flex-start",
        gap: "0.6rem",
        animation: "slideDown 0.3s ease",
        fontFamily: "Manrope, sans-serif",
    }),
};
